microwiki/Models/Shared/BreadcrumbTrailViewModel.cs
using System.Collections.Generic;
using System.Linq;
using MicroWiki.Domain;

namespace MicroWiki.Models
{
    public class BreadcrumbTrailViewModel
    {
        public IEnumerable<BreadcrumbTrailSegment> Segments { get; set; }
            = Enumerable.Empty<BreadcrumbTrailSegment>();
    }
}

microwiki/Controllers/FilesController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Flurl;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MicroWiki.Abstract;
using MicroWiki.Models;
using MicroWiki.Support;
using static MicroWiki.Functions.Functions;

namespace MicroWiki.Controllers
{
    [Authorize]
    public class FilesController : ControllerBase
    {
        private readonly Settings _cfg;
        private readonly IRepository _repository;
        private readonly IFileManager _fileManager;

        public FilesController(
            IOptionsMonitor<Settings> optionsMonitor,
            IRepository repository,
            IFileManager fileManager)
        {
            _cfg = optionsMonitor.CurrentValue;
            _repository = repository;
            _fileManager = fileManager;
        }

        public IActionResult Index()
        {
            var model = new FileListViewModel {
                FileUrls = _fileManager.GetFiles()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(UploadViewModel model)
        {
            var file = model.UploadedFile;

            if (file == null)
            {
                return RedirectToAction(nameof(Upload));
            }

            var uploadedFilePath = await _fileManager.UploadFile(file, $"{model.FileNamePrefix}/{file.FileName}");

            var data = new {
                Filename = Path.GetFileNameWithoutExtension(file.FileName),
                Extension = Path.GetExtension(file.FileName).Trim('.'),
                Url = uploadedFilePath.ToString()
            };

            return Json(data);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUpload(DeleteUploadViewModel model)
        {
            var fileUrl = new Url(NormaliseUrlPath(model.Url));

            var usedInLocations = await _repository.CheckFileUse(fileUrl);

            if (usedInLocations.Any())
            {
                model.InUseByDocuments = usedInLocations;

                return View(model);
            }

            _fileManager.DeleteFile(fileUrl);

            return RedirectToAction(nameof(Index));
        }
    }
}

microwiki/Controllers/TagsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MicroWiki.Abstract;
using MicroWiki.Models;

namespace MicroWiki.Controllers
{
    [Authorize]
    public class TagsController : ControllerBase
    {
        private readonly IRepository _repository;

        public TagsController(IRepository repository) =>
            _repository = repository;

        public async Task<IActionResult> Index()
        {
            var model = new TagIndexViewModel {
                Tags = await _repository.GetTags()
            };

            return View(model);
        }

        public async Task<IActionResult> Manage()
        {
            var model = new TagMergeViewModel {
                Tags = await _repository.GetTags()
            };

            return View(model);
        }

        public async Task<IActionResult> Merge(TagMergeViewModel model)
        {
            await _repository.MergeTags(model.TagID, model.TagIDsToMerge);

            return RedirectToAction(nameof(Manage));
        }
    }
}

microwiki/Controllers/UsersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MicroWiki.Abstract;
using MicroWiki.Models;
using MicroWiki.Support;
using static MicroWiki.Domain.Constants;

namespace MicroWiki.Controllers
{
    public class UsersController : ControllerBase
    {
        private readonly Settings _cfg;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IDateTimeService _dateTimeService;
        private readonly IUserService _userService;

        public UsersController(
            IOptionsMonitor<Settings> optionsMonitor,
            IHttpContextAccessor httpContextAccessor,
            IDateTimeService dateTimeService,
            IUserService userService)
        {
            _cfg = optionsMonitor.CurrentValue;
            _httpContextAccessor = httpContextAccessor;
            _dateTimeService = dateTimeService;
            _userService = userService;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            var model = new LoginViewModel {
                ReturnUrl = returnUrl
            };

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var (valid, id) = await _userService.ValidateLogin(model.Email, model.Password);

            if (!valid)
            {
                return View(model);
            }

            var principal = _userService.GetClaimsPrincipal(id.Value, model.Email);

            var authenticationProperties = new AuthenticationProperties {
                IsPersistent = true,
                ExpiresUtc = _dateTimeService.Now.AddDays(_cfg.PersistentSessionLengthInDays)
            };

            await _httpContextAccessor.HttpContext.SignInAsync(principal, authenticationProperties);

            var returnUrl = !string.IsNullOrWhiteSpace(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl)
                ? model.ReturnUrl
                : SiteRootUrl;

            return Redirect(returnUrl);
        }

        public async Task<IActionResult> Logout()
        {
            await _httpContextAccessor.HttpContext.SignOutAsync();

            return Redirect(SiteRootUrl);
        }
    }
}

microwiki/Controllers/WikiController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MicroWiki.Abstract;
using MicroWiki.Functions;
using MicroWiki.Models;
using static MicroWiki.Domain.Constants;
using static MicroWiki.Functions.Functions;

namespace MicroWiki.Controllers
{
    public class WikiController : ControllerBase
    {
        private readonly ISearchService _searchService;
        private readonly IRepository _repository;

        public WikiController(
            ISearchService searchService,
            IRepository repository)
        {
            _searchService = searchService;
            _repository = repository;
        }

        public async Task<IActionResult> BreadcrumbTrail(Guid id)
        {
            var model = new BreadcrumbTrailViewModel {
                Segments = await _repository.GetBreadcrumbTrail(id)
            };

            return PartialView(nameof(BreadcrumbTrail), model);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Create(Guid parentID)
        {
            var parentDocument = await _repository.ReadDocument(parentID);

            if (parentDocument == null)
            {
                return NotFound();
            }

            var allTags = await _repository.GetTags();

            var model = CreateViewModel.From(parentDocument, allTags);

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.AllTags = await _repository.GetTags();

                return View(model);
            }

            var create = CreateViewModel.ToDocument(model);

            var document = await _repository.CreateDocument(create);

            _searchService.AddDocument(document);

            return Redirect(document.Location);
        }

        public async Task<IActionResult> Read(string location)
        {
            var document = await _repository.ReadDocument(location);

            if (document == null)
            {
                return NotFound();
            }

            if (!document.IsPublic && !User.Identity.IsAuthenticated)
            {
                return new ChallengeResult();
            }

            var breadcrumbTrailData = new BreadcrumbTrailViewModel {
                Segments = await _repository.GetBreadcrumbTrail(document.ID)
            };

            return View(ReadViewModel.From(document, breadcrumbTrailData));
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var document = await _repository.ReadDocument(id);

            if (document == null)
            {
                return NotFound();
            }

            var allTags = await _repository.GetTags();

            return document != null
                ? View(UpdateViewModel.From(document, allTags))
                : NotFound();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Update(UpdateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.AllTags = await _repository.GetTags();

                return View(model);
            }

            var update = UpdateViewModel.ToDocument(model);

            var document = await _repository.UpdateDocument(update);

            _searchService.UpdateDocument(document);

            return Redirect(document.Location);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _repository.DeleteDocument(id);

            _searchService.RemoveDocument(id);

            return Redirect(SiteRootUrl);
        }

        public async Task<IActionResult> Contents()
        {
            var model = new ContentsViewModel {
                Root = await GetSiteMap()
            };

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> EditorTestHarness(Guid? id)
        {
            var model = new EditorTestHarnessViewModel();

            if (id.HasValue)
            {
                var document = await _repository.ReadDocument(id.Value);

                model.Body = document.Body;
            }

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Move(Guid id, Guid newParentID)
        {
            var newLocation = await _repository.MoveDocument(id, newParentID);

            var document = await _repository.ReadDocument(id);

            _searchService.UpdateDocument(document);

            return Json(new { newLocation });
        }

        [Authorize]
        public async Task<IActionResult> MoveDocumentModal(Guid currentDocumentId, string currentDocumentTitle)
        {
            var model = new MoveDocumentModalViewModel {
                ID = currentDocumentId,
                Title = currentDocumentTitle,
                Root = await GetSiteMap()
            };

            return PartialView(nameof(MoveDocumentModal), model);
        }

        [Authorize]
        private async Task<SiteMapDocumentViewModel> GetSiteMap()
        {
            var documents = await _repository.ReadDocuments();

            var root = documents.Single(d => !d.ParentID.HasValue);

            return root.AsTree(documents);
        }
    }
}

microwiki/Views/Shared/_BreadcrumbTrail.cshtml
@model BreadcrumbTrailViewModel

@{ Layout = null; }

<div class="row">
    <div class="col mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                @foreach (var segment in Model.Segments)
                {
                    <li class="breadcrumb-item">
                        @if (segment.ReadOnly)
                        {
                            <span class="breadcrumb-readonly">@segment.Title</span>
                        }
                        else
                        {
                            <a href="@segment.Location">@segment.Title</a>
                        }
                    </li>
                }
            </ol>
        </nav>
    </div>
</div>

microwiki/Views/Shared/_EditorCodeBlockDialog.cshtml
@{ Layout = null; }

<div class="modal" tabindex="-1" role="dialog" id="editor-code-block-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add/Update Code Block</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-2 row">
                    <label for="code-block-language" class="col-sm-2 col-form-label">Language</label>
                    <div class="col-sm-10">
                        <select id="code-block-language" name="code-block-language" class="form-select">
                            <option value="">Plain Text</option>
                            <option value="cs">C#</option>
                            <option value="sql">SQL</option>
                            <option value="ts">TypeScript</option>
                            <option value="js">JavaScript</option>
                            <option value="css">CSS</option>
                            <option value="xml">XML</option>
                            <option value="yaml">YAML</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success">Update Code Block</button>
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

microwiki/Views/Shared/_EditorImageDialog.cshtml
@{ Layout = null; }

<div class="modal" tabindex="-1" role="dialog" id="editor-image-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add/Update Image</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-2 row">
                    <label for="image-url" class="col-sm-2 col-form-label">Url</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="image-url" name="image-url" placeholder="The image URL" value="">
                    </div>
                </div>
                <div class="mb-2 row">
                    <label for="image-text" class="col-sm-2 col-form-label">Alt Text</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="image-alt" name="image-alt" placeholder="The alt text for the image" value="">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success">Update Image</button>
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

microwiki/Views/Shared/_EditorLinkDialog.cshtml
@{ Layout = null; }

<div class="modal" tabindex="-1" role="dialog" id="editor-link-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add/Update Link</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-2 row">
                    <label for="link-text" class="col-sm-2 col-form-label">Text</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="link-text" name="link-text" placeholder="The text for the hyperlink" value="">
                    </div>
                </div>
                <div class="mb-2 row">
                    <label for="link-url" class="col-sm-2 col-form-label">Url</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="link-url" name="link-url" placeholder="The URL to link to" value="">
                    </div>
                </div>
                <div class="mb-2 row">
                    <label for="link-title" class="col-sm-2 col-form-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="link-title" name="link-title" placeholder="A title for the link (optional)" value="">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger">Remove Link</button>
                <button type="button" class="btn btn-success">Update Link</button>
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

microwiki/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.Extensions.Options
@using MicroWiki.Support

@inject IOptionsMonitor<Settings> _cfg

@{
    var configuration = _cfg.CurrentValue;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="noindex">

    @RenderSection("title")

    <link rel="stylesheet" href="~/css/dist/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/dist/main.min.css" />

    @RenderSection("css", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" asp-route="read" asp-route-location="/">@configuration.ApplicationTitle</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="main-nav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-3">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Wiki" asp-action="Contents">Contents</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Tags" asp-action="Index">All Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Tags" asp-action="Manage">Manage Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Files" asp-action="Index">Files</a>
                        </li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item ms-lg-4">
                            <span class="nav-link active">@User.Identity.Name</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Users" asp-action="Logout">Log Out</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Users" asp-action="Login">Log In</a>
                        </li>
                    }
                </ul>
                <form class="d-flex flex-column d-lg-flex flex-lg-row" asp-controller="Search" asp-action="Index" method="get">
                    <input class="form-control me-2 mb-2 mb-lg-0" type="search" placeholder="Search" aria-label="Search" name="query" value="@ViewBag.SearchQuery">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    @RenderSection("modals", required: false)

    @RenderSection("globals", required: false)

    @RenderSection("scripts", required: false)
</body>
</html>